title: 어수혁의_블로그
description: 어수혁의 첫번쨰 블로그

url: 피지컬어수혁.0pe.kr
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
#- title: About
# url: /about

social:
   #github: brianmaierjr
   facebook: https://www.facebook.com/profile.php?id=100015628159438
   email: fishandrew01@naver.com
